######################################################################
##
## Filename: e3_e3_sch_tb.udo
## Created on: Sun Jun 02 13:04:03 RTZ 2 (зима) 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
